/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraryproject;

import javax.swing.JOptionPane;

/**
 *
 * @author majin_000
 */
public class bookEditUI extends javax.swing.JFrame {

    /**
     * Creates new form bookEditUI
     */
    Book myBook = new Book();
    @SuppressWarnings("empty-statement")
    String typeStr = "";
    public bookEditUI(Book book, String editType) {
        typeStr = editType;
        initComponents();
        if (book != null) {
            myBook = book;
            IdTF.setText(String.valueOf(book.getId()));
            IsbnTF.setText(book.getIsbn());
            TitleTF.setText(book.getTitle());
            AuthorTF.setText(book.getAuthor());
            PublisherTF.setText(book.getPublisher().getName());
            CidTF.setText(book.getCid());
            PriceTF.setText(String.valueOf(book.getPrice()));
            QuantityTF.setText(String.valueOf(book.getQuantity()));
            if (book.getHistory() != null && !book.getHistory().isEmpty()) {
                String[] history = book.getHistory().split(";");
                HistoryTA.setColumns(history.length);
                HistoryTA.setLineWrap(true);
                HistoryTA.setWrapStyleWord(true);
                for(String o: history) {
                    HistoryTA.append(o + "\n");
                }
            }
        }
        if (editType.equals("Update")) {
            AddB.setVisible(false);
            UpdateB.setVisible(true);
        }
        if (editType.equals("Add")) {
            AddB.setVisible(true);
            UpdateB.setVisible(false);
        }
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuantityL1 = new javax.swing.JLabel();
        IdL = new javax.swing.JLabel();
        IdTF = new javax.swing.JTextField();
        IsbnL = new javax.swing.JLabel();
        IsbnTF = new javax.swing.JTextField();
        TitleL = new javax.swing.JLabel();
        TitleTF = new javax.swing.JTextField();
        AuthorL = new javax.swing.JLabel();
        AuthorTF = new javax.swing.JTextField();
        PublisherL = new javax.swing.JLabel();
        PublisherTF = new javax.swing.JTextField();
        CidL = new javax.swing.JLabel();
        CidTF = new javax.swing.JTextField();
        PriceL = new javax.swing.JLabel();
        PriceTF = new javax.swing.JTextField();
        QuantityL = new javax.swing.JLabel();
        QuantityTF = new javax.swing.JTextField();
        AddB = new javax.swing.JButton();
        UpdateB = new javax.swing.JButton();
        ResetB = new javax.swing.JButton();
        ExitB = new javax.swing.JButton();
        HistoryL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoryTA = new javax.swing.JTextArea();

        QuantityL1.setText("Quantity: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Library System - Book Edit");

        IdL.setText("ID: ");

        IsbnL.setText("ISBN: ");

        TitleL.setText("Title: ");

        AuthorL.setText("Author: ");

        PublisherL.setText("Publisher: ");

        CidL.setText("Cid: ");

        PriceL.setText("Price: ");

        QuantityL.setText("Quantity: ");

        AddB.setText("Add");
        AddB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBActionPerformed(evt);
            }
        });

        UpdateB.setText("Update");
        UpdateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBActionPerformed(evt);
            }
        });

        ResetB.setText("Reset");
        ResetB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBActionPerformed(evt);
            }
        });

        ExitB.setText("Exit");
        ExitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBActionPerformed(evt);
            }
        });

        HistoryL.setText("History: ");

        HistoryTA.setEditable(false);
        HistoryTA.setColumns(20);
        HistoryTA.setRows(5);
        jScrollPane1.setViewportView(HistoryTA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(QuantityL)
                            .addComponent(PriceL)
                            .addComponent(CidL)
                            .addComponent(PublisherL)
                            .addComponent(AuthorL)
                            .addComponent(TitleL)
                            .addComponent(IsbnL)
                            .addComponent(IdL)
                            .addComponent(HistoryL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IsbnTF, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(IdTF, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(TitleTF, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(AuthorTF, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(PublisherTF, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(CidTF, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(PriceTF, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(QuantityTF, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(UpdateB, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ResetB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ExitB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdL)
                    .addComponent(IdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IsbnL)
                    .addComponent(IsbnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleL)
                    .addComponent(TitleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AuthorL)
                    .addComponent(AuthorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PublisherL)
                    .addComponent(PublisherTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CidL)
                    .addComponent(CidTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceL)
                    .addComponent(PriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityL)
                    .addComponent(QuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(HistoryL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBActionPerformed
        Publisher tmpPublisher = new Publisher();
        tmpPublisher = OracleConnect.doSelectPublisherByName(PublisherTF.getText());
        myBook.setId(Integer.parseInt(IdTF.getText()));
        myBook.setAuthor(AuthorTF.getText());
        myBook.setCid(CidTF.getText());
        myBook.setIsbn(IsbnTF.getText());
        myBook.setPrice(Double.parseDouble(PriceTF.getText()));
        myBook.setPublisher(tmpPublisher);
        myBook.setQuantity(Integer.parseInt(QuantityTF.getText()));
        myBook.setTitle(TitleTF.getText());
        myBook.setHistory("");
        
        if (OracleConnect.doAddBook(myBook)) {
            JOptionPane.showMessageDialog(null, "add a new book completed", "add book success", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "add a new book failed", "add book failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddBActionPerformed

    private void UpdateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBActionPerformed
        myBook.setIsbn(IsbnTF.getText());
        myBook.setAuthor(AuthorTF.getText());
        myBook.setTitle(TitleTF.getText());
        myBook.setCid(CidTF.getText());
        myBook.setPrice(Double.parseDouble(PriceTF.getText()));
        myBook.setQuantity(Integer.parseInt(QuantityTF.getText()));
        myBook.setHistory(HistoryTA.getText());
        Publisher publisher = new Publisher();
        publisher = OracleConnect.doSelectPublisherByName(PublisherTF.getText());
        if (publisher != null) {
            myBook.setPublisher(publisher);
        }
        OracleConnect.doUpdateBook(myBook);
    }//GEN-LAST:event_UpdateBActionPerformed

    private void ResetBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBActionPerformed
        IsbnTF.setText("");
        AuthorTF.setText("");
        TitleTF.setText("");
        CidTF.setText("");
        PriceTF.setText("");
        QuantityTF.setText("");
        HistoryTA.setText("");
        PublisherTF.setText("");
        CidTF.setText("");
        if (typeStr.equals("Add")) {
            IdTF.setText("");
        }
    }//GEN-LAST:event_ResetBActionPerformed

    private void ExitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBActionPerformed
        setVisible(false);
    }//GEN-LAST:event_ExitBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddB;
    private javax.swing.JLabel AuthorL;
    private javax.swing.JTextField AuthorTF;
    private javax.swing.JLabel CidL;
    private javax.swing.JTextField CidTF;
    private javax.swing.JButton ExitB;
    private javax.swing.JLabel HistoryL;
    private javax.swing.JTextArea HistoryTA;
    private javax.swing.JLabel IdL;
    private javax.swing.JTextField IdTF;
    private javax.swing.JLabel IsbnL;
    private javax.swing.JTextField IsbnTF;
    private javax.swing.JLabel PriceL;
    private javax.swing.JTextField PriceTF;
    private javax.swing.JLabel PublisherL;
    private javax.swing.JTextField PublisherTF;
    private javax.swing.JLabel QuantityL;
    private javax.swing.JLabel QuantityL1;
    private javax.swing.JTextField QuantityTF;
    private javax.swing.JButton ResetB;
    private javax.swing.JLabel TitleL;
    private javax.swing.JTextField TitleTF;
    private javax.swing.JButton UpdateB;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
