/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraryproject;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author cstuser
 */
public class categoryManageUI extends javax.swing.JFrame {

    /**
     * Creates new form categoryManageUI
     */
    Category myCategory = new Category();
    categoryEditUI categoryEdit;
    public categoryManageUI() {
        initComponents();
        GetCategoryList();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchTF = new javax.swing.JTextField();
        SearchB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CategoryList = new javax.swing.JList();
        addB = new javax.swing.JButton();
        updateB = new javax.swing.JButton();
        deleteB = new javax.swing.JButton();
        CancelB = new javax.swing.JButton();

        setTitle("Library System- category management");

        SearchB.setText("Search");
        SearchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(CategoryList);

        addB.setText("Add");
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });

        updateB.setText("Update");
        updateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBActionPerformed(evt);
            }
        });

        deleteB.setText("Delete");
        deleteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBActionPerformed(evt);
            }
        });

        CancelB.setText("Cancel");
        CancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateB)
                        .addGap(28, 28, 28)
                        .addComponent(deleteB)
                        .addGap(27, 27, 27)
                        .addComponent(CancelB))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(SearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SearchB))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addB)
                    .addComponent(updateB)
                    .addComponent(deleteB)
                    .addComponent(CancelB))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBActionPerformed
        myCategory = OracleConnect.doSelectCategory(SearchTF.getText());
        if (myCategory != null) {
            categoryEdit = new categoryEditUI(myCategory, "Update");
        } else {
            JOptionPane.showMessageDialog(null, "Not found any record", "Category Search Result", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SearchBActionPerformed

    private void updateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBActionPerformed
        String[] categoryContent = CategoryList.getSelectedValue().toString().split("//");
        myCategory.setId(categoryContent[0]);
        myCategory.setDesc(categoryContent[1]);
        categoryEdit = new categoryEditUI(myCategory, "Update");
    }//GEN-LAST:event_updateBActionPerformed

    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed
        categoryEdit = new categoryEditUI(null, "Add");
    }//GEN-LAST:event_addBActionPerformed

    private void deleteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBActionPerformed
        String[] categoryContent = CategoryList.getSelectedValue().toString().split("//");
        myCategory.setId(categoryContent[0]);
        myCategory.setDesc(categoryContent[1]);
        int result = JOptionPane.showConfirmDialog(null, "Do you want to delete this category", "Category Delete", JOptionPane.WARNING_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            OracleConnect.doDeleteCategory(myCategory);
        }
    }//GEN-LAST:event_deleteBActionPerformed

    private void CancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBActionPerformed
        setVisible(false);
    }//GEN-LAST:event_CancelBActionPerformed

    private void GetCategoryList() {
        ArrayList<Category> categorys = new ArrayList<Category>();
        categorys = OracleConnect.doSelectAllCategory();
        DefaultListModel model = new DefaultListModel();
        if (categorys != null && !categorys.isEmpty()) {
            
            String[] categoryInfo = new String[categorys.size()];
            for(int i = 0; i < categoryInfo.length; i++) {
                categoryInfo[i] = categorys.get(i).getId() + "//" + categorys.get(i).getDesc();
                model.addElement(categoryInfo[i]);
            }
            CategoryList.setModel(model);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelB;
    private javax.swing.JList CategoryList;
    private javax.swing.JButton SearchB;
    private javax.swing.JTextField SearchTF;
    private javax.swing.JButton addB;
    private javax.swing.JButton deleteB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateB;
    // End of variables declaration//GEN-END:variables
}
