/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraryproject;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author cstuser
 */
public class publisherManageUI extends javax.swing.JFrame {

    /**
     * Creates new form publisherManageUI
     */
    publisherEditUI publisherEdit;
    Publisher myPublisher = new Publisher();
    public publisherManageUI() {
        initComponents();
        GetPubliserList();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchTF = new javax.swing.JTextField();
        SearchB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        publisherList = new javax.swing.JList();
        addB = new javax.swing.JButton();
        updateB = new javax.swing.JButton();
        deleteB = new javax.swing.JButton();
        CancelB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Library System - publisher manage");

        SearchB.setText("Search");
        SearchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(publisherList);

        addB.setText("Add");
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });

        updateB.setText("Update");
        updateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBActionPerformed(evt);
            }
        });

        deleteB.setText("Delete");
        deleteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBActionPerformed(evt);
            }
        });

        CancelB.setText("Cancel");
        CancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addB)
                        .addGap(18, 18, 18)
                        .addComponent(updateB)
                        .addGap(18, 18, 18)
                        .addComponent(deleteB)
                        .addGap(18, 18, 18)
                        .addComponent(CancelB))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(SearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(SearchB))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addB)
                    .addComponent(updateB)
                    .addComponent(deleteB)
                    .addComponent(CancelB))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed
        publisherEdit = new publisherEditUI(null, "Add");
    }//GEN-LAST:event_addBActionPerformed

    private void updateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBActionPerformed
        String[] publisherContent = publisherList.getSelectedValue().toString().split("//");
        myPublisher.setPid(Integer.parseInt(publisherContent[0]));
        myPublisher.setName(publisherContent[1]);
        myPublisher.setAddress(publisherContent[2]);
        publisherEdit = new publisherEditUI(myPublisher, "Update");
    }//GEN-LAST:event_updateBActionPerformed

    private void deleteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBActionPerformed
        String[] publisherContent = publisherList.getSelectedValue().toString().split("//");
        myPublisher.setPid(Integer.parseInt(publisherContent[0]));
        myPublisher.setName(publisherContent[1]);
        myPublisher.setAddress(publisherContent[2]);
        int result = JOptionPane.showConfirmDialog(null, "Do you want to delete this publisher", "Publiser Delete", JOptionPane.WARNING_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            OracleConnect.doDeletePublisher(myPublisher);
        }
    }//GEN-LAST:event_deleteBActionPerformed

    private void CancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBActionPerformed
        setVisible(false);
    }//GEN-LAST:event_CancelBActionPerformed

    private void SearchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBActionPerformed
        myPublisher = OracleConnect.doSelectPublisher(Integer.parseInt(SearchTF.getText()));
        if (myPublisher != null) {
            publisherEdit = new publisherEditUI(myPublisher, "Update");
        }
    }//GEN-LAST:event_SearchBActionPerformed
    
    private void GetPubliserList() {
        ArrayList<Publisher> publisers = new ArrayList<Publisher>();
        publisers = OracleConnect.doSelectAllPublisher();
        DefaultListModel model = new DefaultListModel();
        if (publisers != null && !publisers.isEmpty()) {
            
            String[] publisersInfo = new String[publisers.size()];
            for(int i = 0; i < publisersInfo.length; i++) {
                publisersInfo[i] = publisers.get(i).getPid() + "//" + publisers.get(i).getName() + "//" + publisers.get(i).getAddress();
                model.addElement(publisersInfo[i]);
            }
            publisherList.setModel(model);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelB;
    private javax.swing.JButton SearchB;
    private javax.swing.JTextField SearchTF;
    private javax.swing.JButton addB;
    private javax.swing.JButton deleteB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList publisherList;
    private javax.swing.JButton updateB;
    // End of variables declaration//GEN-END:variables
}
