/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraryproject;
import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author cstuser
 */
public class userManagementUI extends javax.swing.JFrame {

    /**
     * Creates new form userManagementUI
     */
    User searchedUser;
    userEditUI userEdit;
    public userManagementUI() {
        searchedUser = new User();
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userSearchTB = new javax.swing.JTextField();
        UserSearchB = new javax.swing.JButton();
        AddUsrB = new javax.swing.JButton();
        UsrListB1 = new javax.swing.JButton();
        ExitB = new javax.swing.JButton();
        SearchedUsrP = new javax.swing.JPanel();
        UpdateSearchedUsrB = new javax.swing.JButton();
        DeleteSearchedUsrB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SearchedUsrTA = new javax.swing.JTextArea();

        setTitle("Library System - User Management");
        setName("userManagementFrm"); // NOI18N

        userSearchTB.setForeground(java.awt.Color.lightGray);
        userSearchTB.setText("search a user by username");
        userSearchTB.setToolTipText("");

        UserSearchB.setText("Search");
        UserSearchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserSearchBActionPerformed(evt);
            }
        });

        AddUsrB.setText("Add New User");
        AddUsrB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUsrBActionPerformed(evt);
            }
        });

        UsrListB1.setText("User List");
        UsrListB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsrListB1ActionPerformed(evt);
            }
        });

        ExitB.setText("Exit");
        ExitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBActionPerformed(evt);
            }
        });

        UpdateSearchedUsrB.setText("Update");
        UpdateSearchedUsrB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSearchedUsrBActionPerformed(evt);
            }
        });

        DeleteSearchedUsrB.setText("Delete");
        DeleteSearchedUsrB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSearchedUsrBActionPerformed(evt);
            }
        });

        SearchedUsrTA.setEditable(false);
        SearchedUsrTA.setColumns(20);
        SearchedUsrTA.setRows(5);
        jScrollPane1.setViewportView(SearchedUsrTA);

        javax.swing.GroupLayout SearchedUsrPLayout = new javax.swing.GroupLayout(SearchedUsrP);
        SearchedUsrP.setLayout(SearchedUsrPLayout);
        SearchedUsrPLayout.setHorizontalGroup(
            SearchedUsrPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchedUsrPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchedUsrPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UpdateSearchedUsrB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteSearchedUsrB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SearchedUsrPLayout.setVerticalGroup(
            SearchedUsrPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchedUsrPLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(UpdateSearchedUsrB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(DeleteSearchedUsrB)
                .addGap(36, 36, 36))
            .addGroup(SearchedUsrPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SearchedUsrP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(AddUsrB)
                                .addGap(26, 26, 26)
                                .addComponent(UsrListB1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ExitB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(userSearchTB, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(UserSearchB)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userSearchTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserSearchB))
                .addGap(18, 18, 18)
                .addComponent(SearchedUsrP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddUsrB)
                    .addComponent(UsrListB1)
                    .addComponent(ExitB))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserSearchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserSearchBActionPerformed
        searchedUser.setUserName(userSearchTB.getText());
        searchedUser = OracleConnect.doSelectUser(userSearchTB.getText());
        if (searchedUser != null) {
            SearchedUsrTA.setText("User Name: " + searchedUser.getUserName() + "\nFirst Name: " + searchedUser.getFname()
                              + "\nLast Name: " + searchedUser.getLname() + "\nEmail: " + searchedUser.getEmail()
                              + "\nMobile Number: " + searchedUser.getPhone() + "\nRole: " + searchedUser.getMyRole());
        }
    }//GEN-LAST:event_UserSearchBActionPerformed

    private void AddUsrBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUsrBActionPerformed
        userEdit = new userEditUI(searchedUser, "Register");// TODO add your handling code here:
    }//GEN-LAST:event_AddUsrBActionPerformed

    private void UsrListB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsrListB1ActionPerformed
        ArrayList<User> users = OracleConnect.doSelectAllUser();
        if (users == null || users.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No any user record", "User List", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String userStr = "";
            int index = 1;
            for (User u: users) {
                userStr += "record" + index + ":\nusername: " + u.getUserName()
                        + "\nfull name: " + u.getFname()
                        + " " + u.getLname() + "\nrole: " + u.getMyRole()
                        + "\n\n";
            }
            JOptionPane.showMessageDialog(null, userStr, "User List", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_UsrListB1ActionPerformed

    private void ExitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_ExitBActionPerformed

    private void UpdateSearchedUsrBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSearchedUsrBActionPerformed
       userEdit = new userEditUI(searchedUser, "update");
    }//GEN-LAST:event_UpdateSearchedUsrBActionPerformed

    private void DeleteSearchedUsrBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSearchedUsrBActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Do you want to delete this user", "User Delete", JOptionPane.WARNING_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            OracleConnect.doDeleteUser(searchedUser);
        }
    }//GEN-LAST:event_DeleteSearchedUsrBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUsrB;
    private javax.swing.JButton DeleteSearchedUsrB;
    private javax.swing.JButton ExitB;
    private javax.swing.JPanel SearchedUsrP;
    private javax.swing.JTextArea SearchedUsrTA;
    private javax.swing.JButton UpdateSearchedUsrB;
    private javax.swing.JButton UserSearchB;
    private javax.swing.JButton UsrListB1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField userSearchTB;
    // End of variables declaration//GEN-END:variables
}
